[project]
name = "casita"
revision = "1.0"

[profiles.default]
AWS_ACCESS_KEY_ID = { description = "Access-key identifier for Casita's optional S3 profile", required = false }
AWS_SECRET_ACCESS_KEY = { description = "Secret access key for Casita's optional S3 profile", required = false }
AWS_SESSION_TOKEN = { description = "Temporary session token for Casita's optional S3 profile", required = false }
